In [2]:
import numpy as np

## Questões Manipulando Arrays

## Explorando Ecossistemas:<br/>

1. Como bióloga marinha, me encontrei em uma expedição nas
profundezas do Oceano Pacífico, onde estávamos estudando a
biodiversidade e a saúde dos recifes de coral. O catálogo abaixo
demonstra dados das espécies encontradas, considere a seguinte
ordem de colunas: <br/>
**ID da espécie, quantidade de representantes encontrados, profundeza,
tamanho médio da espécie.**
* Selecione a segunda coluna com a quantidade de espécies
encontradas e adicione em um array as qtd_especies.
* De qtd_especies selecione apenas as primeiras 3 quantidades e
print.
* Print as 5 últimas quantidades de espécies.
* Crie um array que contenha apenas os tamanhos das espécies e
ordene por ordem crescente.

In [3]:
especies = np.array([[747, 89, 33, 5],
[623, 123, 32, 13],
[501, 22, 49, 2],
[116, 101, 42, 10],
[297, 56, 69, 22],
[613, 64, 27, 7],
[295, 84, 29, 14],
[692, 105, 72, 16],
[229, 103, 35, 5],
[374, 124, 70, 1]])

In [4]:
#Selecionando segunda coluna com a qtd_especies e adicionando a um array
qtd_especies = np.array(especies[:, 1])
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [5]:
# Mostrar de qtd_especies apenas as 3 primeiras quantidades e mostrar
top03_qtd_especies = qtd_especies[0:3]  ## Lembrando que o limite superior tem que ser 1 acima do que quer mostrar
top03_qtd_especies

array([ 89, 123,  22])

In [6]:
#* Print as 5 últimas quantidades de espécies.

last05_qtd_especies = qtd_especies[-5:] ## neste caso 5 e -5, daria a mesma resposta por ser um array de 10
last05_qtd_especies

array([ 64,  84, 105, 103, 124])

In [7]:
# Array que com tamanhos das espécies ordenado crescente.
tamanho_med_especies = np.array(especies[:, 3])
np.sort(tamanho_med_especies)

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [8]:
## Para ordenar em forma decrescente
np.sort(tamanho_med_especies)[::-1]

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

2. Ainda usando o Array de espécies marítimas.
* Usando um index boolean crie um array que contém os dados da
maior espécie encontrada (considerando o seu tamanho), esse
valor corresponde ao valor 22.
* Usando fency index faça um array que contém apenas dados da
espécie com ID 297.
* Usando np.where() faça um array com a linha com dados
correspondentes a espécie com 105 representantes
encontrados.
* Considere a profundeza em que o espécie foi encontrada
substitua valores maiores que 60 com "Profundo”


In [9]:
# Usando o index booleano para identificar na linha 3 a maior especie encontrada
max_especie = max(especies[:, 3])
especies[:, 3] == max_especie

array([False, False, False, False,  True, False, False, False, False,
       False])

In [10]:
# Mostrando os dados da maior especie encontrada
maior_especie = especies[especies[:, 3] == max_especie]
maior_especie

array([[297,  56,  69,  22]])

In [11]:
# Criando uma máscara para demonstrar os dados da especie de ID 297
mask_297 = especies[:, 0] == 297
especies[mask_297]

array([[297,  56,  69,  22]])

In [12]:
# Usando o np.where() para encontrar a especie que tem 105 representantes encontrados.
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

In [13]:
# Substituindo todos os valores > 60 por "Profundo" analisando a coluna profundeza
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

3. Ainda no conjunto 'especies'
* Adicione mais 2 espécies ao array: [[204, 10, 40 , 12],[392, 11, 81, 11]]
* Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: <br/>
[0,1,0,0,0,0,1,0,1,1]
* Faça um array com todas as espécies menos com as com ID 623, 116, 613.

In [14]:
novas_especies = np.array([[204, 10, 40 , 12], [392, 11, 81, 11]])
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [15]:
visao = np.array([0,1,0,0,0,0,1,0,1,1]).reshape((10, 1))
np.concatenate((especies, visao), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

In [16]:
np.delete(especies, [1, 3 ,5], axis=0)

array([[747,  89,  33,   5],
       [501,  22,  49,   2],
       [297,  56,  69,  22],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

## Considerando o array abaixo, responda:

In [17]:
acidentes = np.array([[1, 3, 2],
[0, 1, 0],
[2, 1, 4],
[0, 0, 0],
[1, 1, 0]])

1. O cliente que teve acidente abaixo da média nos últimos 2 anos,
ganhará um desconto no seu seguro. Identifique-os.

In [35]:
media_cliente = np.mean(acidentes, axis=1)

media_geral = np.mean(media_cliente)

cliente_desconto = np.where(media_cliente < media_geral)

cliente_desconto

(array([1, 3, 4], dtype=int64),)

2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

In [32]:
np.where(np.sum(acidentes == 0, axis=1) >= 2)

(array([1, 3], dtype=int64),)

3. Uma professora quer que seus alunos apliquem a função (3x + 2y +
x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e
pede que seja feita essa operação.

In [19]:
array_1 = np.array([3, 7, 10])
array_2 = np.array([2, 9, 7])

def funcao_prof(array_1, array_2):
    return 3*(array_1) + 2*(array_2) + (array_1*array_2)

vetoriza_funcao = np.vectorize(funcao_prof)

resultado = vetoriza_funcao(array_1, array_2)

resultado

array([ 19, 102, 114])

4. A mesma professora percebeu que houve um erro em todas as provas
dos estudantes e esqueceu de anotar a nota de trabalhos
apresentados durante o semestre. Já que foi feito em grupo ela vai
adicionar a mesma nota para todos os estudantes. No array cada
estudante representa uma linha e cada coluna uma prova. Adicione
para cada prova de cada estudante os valores: 1, 2, 1.

In [20]:
#estudante linha / prova coluna

nota = np.array([[1,8,3],
                 [4,5,9], 
                 [2,5,7]])
nota

array([[1, 8, 3],
       [4, 5, 9],
       [2, 5, 7]])

In [21]:
nota_trabalho = np.array([1, 2, 1])
nota_trabalho


array([1, 2, 1])

In [22]:
nota = nota + nota_trabalho
nota


array([[ 2, 10,  4],
       [ 5,  7, 10],
       [ 3,  7,  8]])