In [3]:
import numpy as np

Questões introdutórias

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [8]:
lista_aleatoria = np.random.random((4, 3))
lista_aleatoria

array([[0.63405467, 0.59075528, 0.29231128],
       [0.35358164, 0.39711329, 0.93912718],
       [0.63422752, 0.53031045, 0.47117257],
       [0.62869119, 0.73510653, 0.79392406]])

2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.

In [18]:
lista_aleatoria_int = np.random.randint(0, 75, size=(3, 5))
lista_aleatoria_int

array([[70, 39, 18, 46, 10],
       [10, 14, 65, 40, 12],
       [17, 47,  6, 19, 29]])

4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.

In [22]:
array_4x4 = np.arange(0, 91, 4)
array_4x4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

array_4x4 = np.random.random((4,3))

5. Reduza o array (5,7) a apenas uma dimensão.

In [51]:
array_57 = np.random.random((5, 7))
array_57 = array_57.flatten()
array_57

array([0.65655991, 0.886761  , 0.68248711, 0.49388754, 0.46036507,
       0.45358555, 0.0061553 , 0.46912297, 0.50435547, 0.98685761,
       0.60759045, 0.40947882, 0.88819589, 0.7348689 , 0.10977083,
       0.03098757, 0.21143543, 0.34966874, 0.71046232, 0.22872994,
       0.57058193, 0.9374292 , 0.77347441, 0.63252964, 0.33324713,
       0.9148741 , 0.21829838, 0.91768494, 0.48046389, 0.82199847,
       0.14434178, 0.64266595, 0.82667891, 0.22605586, 0.47987437])

6. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha dos jogos.<br/>
* Os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. 
* Cada cartela terá 12 números (4, 3). 
* Crie um array que representa esse jogo.

In [ ]:
bingo = np.random.randint(1, 31, size=(10, 4, 3))
bingo

7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [ ]:
bingo.reshape((5, 4, 6))