In [2]:
import numpy as np

## Questões Manipulando Arrays

## 1.Explorando Ecossistemas:<br/>

Como bióloga marinha, me encontrei em uma expedição nas
profundezas do Oceano Pacífico, onde estávamos estudando a
biodiversidade e a saúde dos recifes de coral. O catálogo abaixo
demonstra dados das espécies encontradas, considere a seguinte
ordem de colunas: <br/>
**ID da espécie, quantidade de representantes encontrados, profundeza,
tamanho médio da espécie.**
* Selecione a segunda coluna com a quantidade de espécies
encontradas e adicione em um array as qtd_especies.
* De qtd_especies selecione apenas as primeiras 3 quantidades e
print.
* Print as 5 últimas quantidades de espécies.
* Crie um array que contenha apenas os tamanhos das espécies e
ordene por ordem crescente.

In [3]:
especies = np.array([[747, 89, 33, 5],
[623, 123, 32, 13],
[501, 22, 49, 2],
[116, 101, 42, 10],
[297, 56, 69, 22],
[613, 64, 27, 7],
[295, 84, 29, 14],
[692, 105, 72, 16],
[229, 103, 35, 5],
[374, 124, 70, 1]])

In [39]:
#Selecionando segunda coluna com a qtd_especies e adicionando a um array
qtd_especies = np.array(especies[:, 1])
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [40]:
# Mostrar de qtd_especies apenas as 3 primeiras quantidades e mostrar
top03_qtd_especies = qtd_especies[0:3]  ## Lembrando que o limite superior tem que ser 1 acima do que quer mostrar
top03_qtd_especies

array([ 89, 123,  22])

In [42]:
#* Print as 5 últimas quantidades de espécies.

last05_qtd_especies = qtd_especies[5: :]
last05_qtd_especies

array([ 64,  84, 105, 103, 124])

In [44]:
# Array que com tamanhos das espécies ordenado crescente.
tamanho_med_especies = np.array(especies[:, 3])
np.sort(tamanho_med_especies)

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

2. Ainda usando o Array de espécies marítimas.
* Usando um index boolean crie um array que contém os dados da
maior espécie encontrada (considerando o seu tamanho), esse
valor corresponde ao valor 22.
* Usando fency index faça um array que contém apenas dados da
espécie com ID 297.
* Usando np.where() faça um array com a linha com dados
correspondentes a espécie com 105 representantes
encontrados.
* Considere a profundeza em que o espécie foi encontrada
substitua valores maiores que 60 com "Profundo”


## Considerando o array abaixo, responda:

In [2]:
acidentes = np.array([[1, 3, 2],
[0, 1, 0],
[2, 1, 4],
[0, 0, 0],
[1, 1, 0]])

* O cliente que teve acidente abaixo da média nos últimos 2 anos,
ganhará um desconto no seu seguro. Identifique-os.
* Qual cliente teve pelo menos 2 anos sem cometer acidentes?
* Uma professora quer que seus alunos apliquem a função (3x + 2y +
x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e
pede que seja feita essa operação.
* A mesma professora percebeu que houve um erro em todas as provas
dos estudantes e esqueceu de anotar a nota de trabalhos
apresentados durante o semestre. Já que foi feito em grupo ela vai
adicionar a mesma nota para todos os estudantes. No array cada
estudante representa uma linha e cada coluna uma prova. Adicione
para cada prova de cada estudante os valores: 1, 2, 1.